//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gardener.Core.Authorization.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthorizationLocalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthorizationLocalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gardener.Core.Authorization.Resources.AuthorizationLocalResource", typeof(AuthorizationLocalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ip 的本地化字符串。
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastLoginLog 的本地化字符串。
        /// </summary>
        public static string LastLoginLog {
            get {
                return ResourceManager.GetString("LastLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginClientType 的本地化字符串。
        /// </summary>
        public static string LoginClientType {
            get {
                return ResourceManager.GetString("LoginClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginFailReason 的本地化字符串。
        /// </summary>
        public static string LoginFailReason {
            get {
                return ResourceManager.GetString("LoginFailReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginLog 的本地化字符串。
        /// </summary>
        public static string LoginLog {
            get {
                return ResourceManager.GetString("LoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginStatus 的本地化字符串。
        /// </summary>
        public static string LoginStatus {
            get {
                return ResourceManager.GetString("LoginStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginTime 的本地化字符串。
        /// </summary>
        public static string LoginTime {
            get {
                return ResourceManager.GetString("LoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeed 的本地化字符串。
        /// </summary>
        public static string Succeed {
            get {
                return ResourceManager.GetString("Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserLocked 的本地化字符串。
        /// </summary>
        public static string UserLocked {
            get {
                return ResourceManager.GetString("UserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserNotExist 的本地化字符串。
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WrongPassword 的本地化字符串。
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
