global using Gardener.Core.DependencyInjection;
global using Gardener.Core.Util;
global using Gardener.Core.Enums;
global using Gardener.Core.Client.Services;
global using Gardener.Core.Client.OperationDialog;
global using Gardener.Core.Client.Components.PageBaseClass;
global using Gardener.Weighbridge.Dtos;
global using Gardener.Weighbridge.Services;
global using Gardener.Weighbridge.Resources;