//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTShang.Iot.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IotLocalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IotLocalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gardener.Iot.Resources.IotLocalResource", typeof(IotLocalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AdministrativeAction 的本地化字符串。
        /// </summary>
        public static string AdministrativeAction {
            get {
                return ResourceManager.GetString("AdministrativeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alias 的本地化字符串。
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuthenticationInformation 的本地化字符串。
        /// </summary>
        public static string AuthenticationInformation {
            get {
                return ResourceManager.GetString("AuthenticationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClientId 的本地化字符串。
        /// </summary>
        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting 的本地化字符串。
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectingDeviceConnection 的本地化字符串。
        /// </summary>
        public static string ConnectingDeviceConnection {
            get {
                return ResourceManager.GetString("ConnectingDeviceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectionRateExceeded 的本地化字符串。
        /// </summary>
        public static string ConnectionRateExceeded {
            get {
                return ResourceManager.GetString("ConnectionRateExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectionType 的本地化字符串。
        /// </summary>
        public static string ConnectionType {
            get {
                return ResourceManager.GetString("ConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContentType 的本地化字符串。
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device 的本地化字符串。
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceAccount 的本地化字符串。
        /// </summary>
        public static string DeviceAccount {
            get {
                return ResourceManager.GetString("DeviceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceClientEndpoint 的本地化字符串。
        /// </summary>
        public static string DeviceClientEndpoint {
            get {
                return ResourceManager.GetString("DeviceClientEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceClientId 的本地化字符串。
        /// </summary>
        public static string DeviceClientId {
            get {
                return ResourceManager.GetString("DeviceClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceClientIp 的本地化字符串。
        /// </summary>
        public static string DeviceClientIp {
            get {
                return ResourceManager.GetString("DeviceClientIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceConnectFailed 的本地化字符串。
        /// </summary>
        public static string DeviceConnectFailed {
            get {
                return ResourceManager.GetString("DeviceConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceConnecting 的本地化字符串。
        /// </summary>
        public static string DeviceConnecting {
            get {
                return ResourceManager.GetString("DeviceConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceConnection 的本地化字符串。
        /// </summary>
        public static string DeviceConnection {
            get {
                return ResourceManager.GetString("DeviceConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceConnectionId 的本地化字符串。
        /// </summary>
        public static string DeviceConnectionId {
            get {
                return ResourceManager.GetString("DeviceConnectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceConnectionState 的本地化字符串。
        /// </summary>
        public static string DeviceConnectionState {
            get {
                return ResourceManager.GetString("DeviceConnectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceConnectionType 的本地化字符串。
        /// </summary>
        public static string DeviceConnectionType {
            get {
                return ResourceManager.GetString("DeviceConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceConnectSucceed 的本地化字符串。
        /// </summary>
        public static string DeviceConnectSucceed {
            get {
                return ResourceManager.GetString("DeviceConnectSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceData 的本地化字符串。
        /// </summary>
        public static string DeviceData {
            get {
                return ResourceManager.GetString("DeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceDisconnect 的本地化字符串。
        /// </summary>
        public static string DeviceDisconnect {
            get {
                return ResourceManager.GetString("DeviceDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceDisconnectReason 的本地化字符串。
        /// </summary>
        public static string DeviceDisconnectReason {
            get {
                return ResourceManager.GetString("DeviceDisconnectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceDisconnectReasonDescription 的本地化字符串。
        /// </summary>
        public static string DeviceDisconnectReasonDescription {
            get {
                return ResourceManager.GetString("DeviceDisconnectReasonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceDisconnectTime 的本地化字符串。
        /// </summary>
        public static string DeviceDisconnectTime {
            get {
                return ResourceManager.GetString("DeviceDisconnectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceGroup 的本地化字符串。
        /// </summary>
        public static string DeviceGroup {
            get {
                return ResourceManager.GetString("DeviceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceGroupId 的本地化字符串。
        /// </summary>
        public static string DeviceGroupId {
            get {
                return ResourceManager.GetString("DeviceGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceHasBeenBound 的本地化字符串。
        /// </summary>
        public static string DeviceHasBeenBound {
            get {
                return ResourceManager.GetString("DeviceHasBeenBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceId 的本地化字符串。
        /// </summary>
        public static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceIdentityIsInvalid 的本地化字符串。
        /// </summary>
        public static string DeviceIdentityIsInvalid {
            get {
                return ResourceManager.GetString("DeviceIdentityIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceIdentityIsNullOrEmpty 的本地化字符串。
        /// </summary>
        public static string DeviceIdentityIsNullOrEmpty {
            get {
                return ResourceManager.GetString("DeviceIdentityIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceIdOrSecretKeyIsInvalid 的本地化字符串。
        /// </summary>
        public static string DeviceIdOrSecretKeyIsInvalid {
            get {
                return ResourceManager.GetString("DeviceIdOrSecretKeyIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceIdOrSecretKeyIsNullOrEmpty 的本地化字符串。
        /// </summary>
        public static string DeviceIdOrSecretKeyIsNullOrEmpty {
            get {
                return ResourceManager.GetString("DeviceIdOrSecretKeyIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceLastPingTime 的本地化字符串。
        /// </summary>
        public static string DeviceLastPingTime {
            get {
                return ResourceManager.GetString("DeviceLastPingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceLastPushDataTime 的本地化字符串。
        /// </summary>
        public static string DeviceLastPushDataTime {
            get {
                return ResourceManager.GetString("DeviceLastPushDataTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceTag 的本地化字符串。
        /// </summary>
        public static string DeviceTag {
            get {
                return ResourceManager.GetString("DeviceTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DownstreamConfig 的本地化字符串。
        /// </summary>
        public static string DownstreamConfig {
            get {
                return ResourceManager.GetString("DownstreamConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExtendData 的本地化字符串。
        /// </summary>
        public static string ExtendData {
            get {
                return ResourceManager.GetString("ExtendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GenerateConnectConfig 的本地化字符串。
        /// </summary>
        public static string GenerateConnectConfig {
            get {
                return ResourceManager.GetString("GenerateConnectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heartbeat 的本地化字符串。
        /// </summary>
        public static string Heartbeat {
            get {
                return ResourceManager.GetString("Heartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InputContentType 的本地化字符串。
        /// </summary>
        public static string InputContentType {
            get {
                return ResourceManager.GetString("InputContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsHex 的本地化字符串。
        /// </summary>
        public static string IsHex {
            get {
                return ResourceManager.GetString("IsHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KeepAliveTimeout 的本地化字符串。
        /// </summary>
        public static string KeepAliveTimeout {
            get {
                return ResourceManager.GetString("KeepAliveTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 menu:iot 的本地化字符串。
        /// </summary>
        public static string menu_iot {
            get {
                return ResourceManager.GetString("menu:iot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 menu:iot_device 的本地化字符串。
        /// </summary>
        public static string menu_iot_device {
            get {
                return ResourceManager.GetString("menu:iot_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 menu:iot_device_connection 的本地化字符串。
        /// </summary>
        public static string menu_iot_device_connection {
            get {
                return ResourceManager.GetString("menu:iot_device_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 menu:iot_device_group 的本地化字符串。
        /// </summary>
        public static string menu_iot_device_group {
            get {
                return ResourceManager.GetString("menu:iot_device_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 menu:iot_device_system_log 的本地化字符串。
        /// </summary>
        public static string menu_iot_device_system_log {
            get {
                return ResourceManager.GetString("menu:iot_device_system_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 menu:iot_product 的本地化字符串。
        /// </summary>
        public static string menu_iot_product {
            get {
                return ResourceManager.GetString("menu:iot_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NormalDisconnection 的本地化字符串。
        /// </summary>
        public static string NormalDisconnection {
            get {
                return ResourceManager.GetString("NormalDisconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotAuthorized 的本地化字符串。
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order 的本地化字符串。
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ParentId 的本地化字符串。
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product 的本地化字符串。
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductDescription 的本地化字符串。
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductId 的本地化字符串。
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductImages 的本地化字符串。
        /// </summary>
        public static string ProductImages {
            get {
                return ResourceManager.GetString("ProductImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductName 的本地化字符串。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductType 的本地化字符串。
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductVersion 的本地化字符串。
        /// </summary>
        public static string ProductVersion {
            get {
                return ResourceManager.GetString("ProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SecretKey 的本地化字符串。
        /// </summary>
        public static string SecretKey {
            get {
                return ResourceManager.GetString("SecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServerBusy 的本地化字符串。
        /// </summary>
        public static string ServerBusy {
            get {
                return ResourceManager.GetString("ServerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowConnections 的本地化字符串。
        /// </summary>
        public static string ShowConnections {
            get {
                return ResourceManager.GetString("ShowConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowLogs 的本地化字符串。
        /// </summary>
        public static string ShowLogs {
            get {
                return ResourceManager.GetString("ShowLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StorageHistoryData 的本地化字符串。
        /// </summary>
        public static string StorageHistoryData {
            get {
                return ResourceManager.GetString("StorageHistoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemLogType 的本地化字符串。
        /// </summary>
        public static string SystemLogType {
            get {
                return ResourceManager.GetString("SystemLogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag 的本地化字符串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpstreamConfig 的本地化字符串。
        /// </summary>
        public static string UpstreamConfig {
            get {
                return ResourceManager.GetString("UpstreamConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserProperties 的本地化字符串。
        /// </summary>
        public static string UserProperties {
            get {
                return ResourceManager.GetString("UserProperties", resourceCulture);
            }
        }
    }
}
