//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTShang.Core.Printer.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrinterLocalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrinterLocalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gardener.Core.Printer.Resources.PrinterLocalResource", typeof(PrinterLocalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BasicInformation 的本地化字符串。
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommandJson 的本地化字符串。
        /// </summary>
        public static string CommandJson {
            get {
                return ResourceManager.GetString("CommandJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintTemplate 的本地化字符串。
        /// </summary>
        public static string PrintTemplate {
            get {
                return ResourceManager.GetString("PrintTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplateContent 的本地化字符串。
        /// </summary>
        public static string TemplateContent {
            get {
                return ResourceManager.GetString("TemplateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplateHeight 的本地化字符串。
        /// </summary>
        public static string TemplateHeight {
            get {
                return ResourceManager.GetString("TemplateHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplateKey 的本地化字符串。
        /// </summary>
        public static string TemplateKey {
            get {
                return ResourceManager.GetString("TemplateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplateName 的本地化字符串。
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplatePreviewImage 的本地化字符串。
        /// </summary>
        public static string TemplatePreviewImage {
            get {
                return ResourceManager.GetString("TemplatePreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplateResultType 的本地化字符串。
        /// </summary>
        public static string TemplateResultType {
            get {
                return ResourceManager.GetString("TemplateResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplateType 的本地化字符串。
        /// </summary>
        public static string TemplateType {
            get {
                return ResourceManager.GetString("TemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TemplateWidth 的本地化字符串。
        /// </summary>
        public static string TemplateWidth {
            get {
                return ResourceManager.GetString("TemplateWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
    }
}
