//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gardener.Weighbridge.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WeighbridgeLocalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeighbridgeLocalResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gardener.Weighbridge.Resources.WeighbridgeLocalResource", typeof(WeighbridgeLocalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AfterRecordId 的本地化字符串。
        /// </summary>
        public static string AfterRecordId {
            get {
                return ResourceManager.GetString("AfterRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AfterRecordTime 的本地化字符串。
        /// </summary>
        public static string AfterRecordTime {
            get {
                return ResourceManager.GetString("AfterRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Axles 的本地化字符串。
        /// </summary>
        public static string Axles {
            get {
                return ResourceManager.GetString("Axles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BeforeRecordId 的本地化字符串。
        /// </summary>
        public static string BeforeRecordId {
            get {
                return ResourceManager.GetString("BeforeRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BeforeRecordTime 的本地化字符串。
        /// </summary>
        public static string BeforeRecordTime {
            get {
                return ResourceManager.GetString("BeforeRecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChangeWeight 的本地化字符串。
        /// </summary>
        public static string ChangeWeight {
            get {
                return ResourceManager.GetString("ChangeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChannelNumber 的本地化字符串。
        /// </summary>
        public static string ChannelNumber {
            get {
                return ResourceManager.GetString("ChannelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commodity 的本地化字符串。
        /// </summary>
        public static string Commodity {
            get {
                return ResourceManager.GetString("Commodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommodityCode 的本地化字符串。
        /// </summary>
        public static string CommodityCode {
            get {
                return ResourceManager.GetString("CommodityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommodityDescription 的本地化字符串。
        /// </summary>
        public static string CommodityDescription {
            get {
                return ResourceManager.GetString("CommodityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommodityName 的本地化字符串。
        /// </summary>
        public static string CommodityName {
            get {
                return ResourceManager.GetString("CommodityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommodityNameNotMatchCode 的本地化字符串。
        /// </summary>
        public static string CommodityNameNotMatchCode {
            get {
                return ResourceManager.GetString("CommodityNameNotMatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommodityWeight 的本地化字符串。
        /// </summary>
        public static string CommodityWeight {
            get {
                return ResourceManager.GetString("CommodityWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfigNameRepeat 的本地化字符串。
        /// </summary>
        public static string ConfigNameRepeat {
            get {
                return ResourceManager.GetString("ConfigNameRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contacts 的本地化字符串。
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DefaultPrintTemplateKey 的本地化字符串。
        /// </summary>
        public static string DefaultPrintTemplateKey {
            get {
                return ResourceManager.GetString("DefaultPrintTemplateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DefaultWeighbridgeConfigId 的本地化字符串。
        /// </summary>
        public static string DefaultWeighbridgeConfigId {
            get {
                return ResourceManager.GetString("DefaultWeighbridgeConfigId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device 的本地化字符串。
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceDoesNotExist 的本地化字符串。
        /// </summary>
        public static string DeviceDoesNotExist {
            get {
                return ResourceManager.GetString("DeviceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceId 的本地化字符串。
        /// </summary>
        public static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceIdCannotBeEmpty 的本地化字符串。
        /// </summary>
        public static string DeviceIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("DeviceIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeviceIds 的本地化字符串。
        /// </summary>
        public static string DeviceIds {
            get {
                return ResourceManager.GetString("DeviceIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Devices 的本地化字符串。
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DivisionValue 的本地化字符串。
        /// </summary>
        public static string DivisionValue {
            get {
                return ResourceManager.GetString("DivisionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver 的本地化字符串。
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ErrorCoefficient 的本地化字符串。
        /// </summary>
        public static string ErrorCoefficient {
            get {
                return ResourceManager.GetString("ErrorCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoadedGoods 的本地化字符串。
        /// </summary>
        public static string LoadedGoods {
            get {
                return ResourceManager.GetString("LoadedGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoadGoods 的本地化字符串。
        /// </summary>
        public static string LoadGoods {
            get {
                return ResourceManager.GetString("LoadGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaximumLoad 的本地化字符串。
        /// </summary>
        public static string MaximumLoad {
            get {
                return ResourceManager.GetString("MaximumLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoLoadGoods 的本地化字符串。
        /// </summary>
        public static string NoLoadGoods {
            get {
                return ResourceManager.GetString("NoLoadGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnLine 的本地化字符串。
        /// </summary>
        public static string OnLine {
            get {
                return ResourceManager.GetString("OnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OperatorName 的本地化字符串。
        /// </summary>
        public static string OperatorName {
            get {
                return ResourceManager.GetString("OperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PlateNumber 的本地化字符串。
        /// </summary>
        public static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TareWeight 的本地化字符串。
        /// </summary>
        public static string TareWeight {
            get {
                return ResourceManager.GetString("TareWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tel 的本地化字符串。
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TodayWeighNumber 的本地化字符串。
        /// </summary>
        public static string TodayWeighNumber {
            get {
                return ResourceManager.GetString("TodayWeighNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tonne 的本地化字符串。
        /// </summary>
        public static string Tonne {
            get {
                return ResourceManager.GetString("Tonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnloadedGoods 的本地化字符串。
        /// </summary>
        public static string UnloadedGoods {
            get {
                return ResourceManager.GetString("UnloadedGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserId 的本地化字符串。
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserWeighbridgeConfig 的本地化字符串。
        /// </summary>
        public static string UserWeighbridgeConfig {
            get {
                return ResourceManager.GetString("UserWeighbridgeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VehicleType 的本地化字符串。
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VehicleWeighingConfig 的本地化字符串。
        /// </summary>
        public static string VehicleWeighingConfig {
            get {
                return ResourceManager.GetString("VehicleWeighingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeighbridgeConfig 的本地化字符串。
        /// </summary>
        public static string WeighbridgeConfig {
            get {
                return ResourceManager.GetString("WeighbridgeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeighbridgeConfigId 的本地化字符串。
        /// </summary>
        public static string WeighbridgeConfigId {
            get {
                return ResourceManager.GetString("WeighbridgeConfigId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeighbridgeDeviceConfig 的本地化字符串。
        /// </summary>
        public static string WeighbridgeDeviceConfig {
            get {
                return ResourceManager.GetString("WeighbridgeDeviceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeighingNumber 的本地化字符串。
        /// </summary>
        public static string WeighingNumber {
            get {
                return ResourceManager.GetString("WeighingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeighingRecord 的本地化字符串。
        /// </summary>
        public static string WeighingRecord {
            get {
                return ResourceManager.GetString("WeighingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeighingRecordId 的本地化字符串。
        /// </summary>
        public static string WeighingRecordId {
            get {
                return ResourceManager.GetString("WeighingRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeighingRecordLog 的本地化字符串。
        /// </summary>
        public static string WeighingRecordLog {
            get {
                return ResourceManager.GetString("WeighingRecordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeighingStatus 的本地化字符串。
        /// </summary>
        public static string WeighingStatus {
            get {
                return ResourceManager.GetString("WeighingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeighingTime 的本地化字符串。
        /// </summary>
        public static string WeighingTime {
            get {
                return ResourceManager.GetString("WeighingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeighNumber 的本地化字符串。
        /// </summary>
        public static string WeighNumber {
            get {
                return ResourceManager.GetString("WeighNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight 的本地化字符串。
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeightChange 的本地化字符串。
        /// </summary>
        public static string WeightChange {
            get {
                return ResourceManager.GetString("WeightChange", resourceCulture);
            }
        }
    }
}
